name: Call Markdown Lint Check Workflow

on:
  pull_request:
    types:
    - opened
    - synchronize
    - reopened


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  call-lint-check:
    uses: Security-Knowledge-Framework/GH-actions-markdown-linting/.github/workflows/steps.yml@main
    with:
      ref: ${{ github.head_ref }}
      repository: ${{ github.repository }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
